#!/bin/sh

# include rstudio-server to get pandoc

/usr/bin/invoke_app "$@" -t spiroshinyapp2 \
    -u R-3.4.0 \
    -u rstudio-server-1.0.143 \
    -u wrwroxy-0.1 \
    -u wrapprun-0.1 \
    -w "none" \
    -c "xview -fullscreen -onroot \${R_LOGO_PATH}" \
    -c "wrwroxy --stream-log --logfile /dev/null" \
    -C "wrapprun --port 8001 --type shiny @tool/bin"
