#!/bin/sh

# include rstudio-server to get pandoc

/usr/bin/invoke_app "$@" -t spiroshinyapp2 \
    -u R-3.2.1 \
    -u rstudio-server-1.0.44 \
    -u wrwroxy-0.1 \
    -w "none" \
    -c "xview -fullscreen -onroot @tool/data/Rlogo-1.png" \
    -c "wrwroxy --listenHost 0.0.0.0 --listenPort 8000 --forwardHost 127.0.0.1 --forwardPort 8001 --stream-log --logfile /dev/null" \
    -C "Rscript @tool/bin/runRShiny.R --host 0.0.0.0 --port 8001 @tool/bin"
